import { makeQuestions } from './build';
const P96 = { book: 'SB', page: 96, ref: 'Grammar Bank 3A / 3B' };
const P98 = { book: 'SB', page: 98, ref: 'Grammar Bank 4A / 4B' };
const nounDrafts = [
    { q: 'It’s ___ umbrella.', o: ['a', 'an', 'the'], a: 1,
        e: 'Umbrella begins with a vowel sound, so we use an.', c: 'a-an', d: 1 },
    { q: 'It’s ___ key.', o: ['an', 'a', 'some'], a: 1,
        e: 'Key begins with a consonant sound, so we use a.', c: 'a-an', d: 1 },
    { q: 'It’s ___ ID card.', o: ['a', 'an', 'the'], a: 1,
        e: 'ID begins with a vowel sound, so we use an.', c: 'a-an', d: 3 },
    { q: 'She has ___ old camera.', o: ['a', 'an', 'some'], a: 1,
        e: 'Old begins with a vowel sound, so we use an.', c: 'a-an', d: 3 },
    { q: 'That’s ___ new laptop.', o: ['an', 'a', 'some'], a: 1,
        e: 'New begins with a consonant sound, so we use a.', c: 'a-an' },
    { q: 'What are they? They’re ___.', o: ['watchs', 'watches', 'watch'], a: 1,
        e: 'After ch we add -es: watches.', c: 'plurals', d: 3 },
    { q: 'What are they? They’re ___.', o: ['dictionaries', 'dictionarys', 'dictionaryes'], a: 0,
        e: 'A consonant plus y becomes -ies: dictionaries.', c: 'plurals', d: 3 },
    { q: 'One key, two ___.', o: ['keies', 'keys', 'keyes'], a: 1,
        e: 'A vowel plus y just adds -s: keys.', c: 'plurals' },
    { q: 'One class, two ___.', o: ['classes', 'classs', 'classies'], a: 0,
        e: 'After ss we add -es: classes.', c: 'plurals' },
    { q: 'One country, two ___.', o: ['countrys', 'countryes', 'countries'], a: 2,
        e: 'A consonant plus y becomes -ies: countries.', c: 'plurals' },
    { q: 'One child, two ___.', o: ['childs', 'children', 'childes'], a: 1,
        e: 'Child has the irregular plural children.', c: 'plurals' },
    { q: 'One woman, two ___.', o: ['womans', 'women', 'womens'], a: 1,
        e: 'Woman has the irregular plural women.', c: 'plurals' },
    { q: 'One person, two ___.', o: ['people', 'persons', 'peoples'], a: 0,
        e: 'Person has the irregular plural people.', c: 'plurals' },
    { q: 'One man, two ___.', o: ['mans', 'men', 'mens'], a: 1,
        e: 'Man has the irregular plural men.', c: 'plurals' },
    { q: 'Look at ___ board, please.', o: ['a', 'an', 'the'], a: 2,
        e: 'We use the for something we both know about.', c: 'a-an' },
];
const thisThatDrafts = [
    { q: 'What’s ___? It’s a key. (in my hand)', o: ['this', 'that', 'those'], a: 0,
        e: 'We use this for one thing near us.', c: 'near-far', d: 1 },
    { q: 'What are ___? They’re keys. (in my hand)', o: ['this', 'these', 'that'], a: 1,
        e: 'We use these for more than one thing near us.', c: 'near-far' },
    { q: 'What’s ___? It’s a cat. (over there)', o: ['this', 'these', 'that'], a: 2,
        e: 'We use that for one thing that is not near us.', c: 'near-far' },
    { q: 'What are ___? They’re cats. (over there)', o: ['those', 'these', 'this'], a: 0,
        e: 'We use those for more than one thing that is not near us.', c: 'near-far' },
    { q: '___ book is very nice.', o: ['These', 'This', 'Those'], a: 1,
        e: 'Book is singular and near, so we use This.', c: 'near-far' },
    { q: 'Who are ___ girls over there?', o: ['this', 'that', 'those'], a: 2,
        e: 'Girls is plural and far, so we use those.', c: 'near-far' },
    { q: '___ is my brother.', o: ['This', 'These', 'Those'], a: 0,
        e: 'We also use this for people: This is my brother.', c: 'near-far' },
    { q: 'Which sentence is correct?',
        o: ['These is my books.', 'These are my books.', 'This are my books.'], a: 1,
        e: 'These is plural, so it takes are.', c: 'near-far', d: 3 },
];
const possessiveDrafts = [
    { q: 'I’m from Spain. ___ name is Ana.', o: ['My', 'Me', 'Mine'], a: 0,
        e: 'The possessive adjective for I is my.', c: 'poss-adj', d: 1 },
    { q: 'She’s Italian. ___ name is Clara.', o: ['His', 'Her', 'Its'], a: 1,
        e: 'The possessive adjective for she is her.', c: 'poss-adj', d: 1 },
    { q: 'He’s from Rome. ___ name is Marco.', o: ['Her', 'His', 'Its'], a: 1,
        e: 'The possessive adjective for he is his.', c: 'poss-adj', d: 1 },
    { q: 'It’s a French restaurant. ___ name is Chez Marcelle.', o: ['It’s', 'Its', 'His'], a: 1,
        e: 'Its is the possessive. It’s means it is.', c: 'its-vs-its', d: 3 },
    { q: 'We’re from Brazil. ___ names are Selma and Luis.', o: ['Our', 'Ours', 'Us'], a: 0,
        e: 'The possessive adjective for we is our.', c: 'poss-adj' },
    { q: 'They’re from Mexico. ___ names are Pedro and Maria.', o: ['Theirs', 'Their', 'They’re'], a: 1,
        e: 'The possessive adjective for they is their.', c: 'poss-adj' },
    { q: 'Which sentence is correct?',
        o: ['Their coats are black.', 'Theirs coats are black.', 'They coats are black.'], a: 0,
        e: 'We say their coats, not theirs coats.', c: 'poss-adj', d: 3 },
    { q: 'This is ___ car.', o: ['Jack’s', 'Jacks', 'Jacks’'], a: 0,
        e: 'We add ’s after a person: Jack’s car.', c: 'poss-s' },
    { q: 'This is my ___ house. (I have two brothers)', o: ['brother’s', 'brothers’', 'brothers'], a: 1,
        e: 'After a plural person we add just an apostrophe: my brothers’ house.', c: 'poss-s', d: 3 },
    { q: 'My ___ name is Molly.', o: ['sisters', 'sister’s', 'sisters’'], a: 1,
        e: 'One sister takes ’s.', c: 'poss-s' },
    { q: '___ American. Her name’s Emma.', o: ['She’s', 'Her', 'Hers'], a: 0,
        e: 'Here ’s means is: She is American.', c: 'its-vs-its', d: 3 },
];
const adjectiveDrafts = [
    { q: 'Which sentence is correct?',
        o: ['An Audi expensive is.', 'An Audi is expensive.', 'An Audi is expensive car.'], a: 1,
        e: 'Adjectives come after the verb be.', c: 'adj-position', d: 1 },
    { q: 'Which sentence is correct?',
        o: ['It’s a car fast.', 'It’s a fast car.', 'It’s fast a car.'], a: 1,
        e: 'Adjectives come before the noun.', c: 'adj-position' },
    { q: 'Which sentence is correct?',
        o: ['They’re olds houses.', 'They’re old houses.', 'They’re houses old.'], a: 1,
        e: 'Adjectives never take -s.', c: 'adj-position', d: 3 },
    { q: 'My glasses are ___.', o: ['news', 'new', 'a new'], a: 1,
        e: 'Adjectives are the same for singular and plural.', c: 'adj-position' },
    { q: 'What’s the opposite of new?', o: ['old', 'big', 'clean'], a: 0,
        e: 'The opposite of new is old.', c: 'opposites', d: 1 },
    { q: 'What’s the opposite of expensive?', o: ['dirty', 'cheap', 'slow'], a: 1,
        e: 'The opposite of expensive is cheap.', c: 'opposites' },
    { q: 'What’s the opposite of difficult?', o: ['easy', 'ugly', 'short'], a: 0,
        e: 'The opposite of difficult is easy.', c: 'opposites' },
    { q: 'What’s the opposite of beautiful?', o: ['small', 'ugly', 'cold'], a: 1,
        e: 'The opposite of beautiful is ugly.', c: 'opposites' },
    { q: 'A Ferrari is ___ expensive car.', o: ['a very', 'very a', 'very'], a: 0,
        e: 'We say a very expensive car.', c: 'adj-position', d: 3 },
];
const cfg = (topicId, unit, slug, source) => ({ topicId, categoryId: 'grammar', unit, type: 'gap-fill', source, slug });
export const gramNounsAAn = makeQuestions(cfg('beg-g-nouns-a-an', 3, 'na', P96), nounDrafts);
export const gramThisThat = makeQuestions(cfg('beg-g-this-that-these-those', 3, 'tt', P96), thisThatDrafts);
export const gramPossessives = makeQuestions(cfg('beg-g-possessives', 4, 'po', P98), possessiveDrafts);
export const gramAdjectives = makeQuestions(cfg('beg-g-adjectives', 4, 'ad', P98), adjectiveDrafts);
