import { makeQuestions } from './build';
const SRC = { book: 'SB', page: 130, ref: 'Vocabulary Bank — Hotels' };
const drafts = [
    // --- definitions -------------------------------------------------------------
    { q: 'You use this to go to the fifth floor.', o: ['a park', 'a lamp', 'a lift'], a: 2,
        e: 'A lift takes you up and down inside a building.', c: 'definition' },
    { q: 'You usually go here to do exercise.', o: ['a supermarket', 'reception', 'a gym'], a: 2,
        e: 'A gym is the place for exercise.', c: 'definition' },
    { q: 'You can see this from the window in a good hotel.', o: ['a toilet', 'a view', 'a shop'], a: 1,
        e: 'A view is what you see from a window.', c: 'definition' },
    { q: 'You can stay here.', o: ['a bathroom', 'a kitchen', 'a hotel'], a: 2,
        e: 'You stay in a hotel.', c: 'definition' },
    { q: 'You use this to turn on or turn off the TV.', o: ['a remote control', 'a double bed', 'wi-fi'], a: 0,
        e: 'A remote control turns the TV on and off.', c: 'definition' },
    { q: 'There is a bath and a shower and some towels in this place.', o: ['a bedroom', 'a gym', 'a bathroom'], a: 2,
        e: 'A bathroom has a bath, a shower and towels.', c: 'definition' },
    { q: 'It is on the bed and you can sleep on it.', o: ['a towel', 'a lamp', 'a pillow'], a: 2,
        e: 'A pillow is on the bed for your head.', c: 'definition' },
    { q: 'There are waiters in this place. You can have dinner here.', o: ['a restaurant', 'reception', 'a spa'], a: 0,
        e: 'A restaurant has waiters and you have dinner there.', c: 'definition' },
    { q: 'You go here when you arrive at a hotel.', o: ['a garden', 'reception', 'a car park'], a: 1,
        e: 'You go to reception when you arrive.', c: 'definition' },
    { q: 'You leave your car here.', o: ['a car park', 'a gift shop', 'a bar'], a: 0,
        e: 'A car park is for cars.', c: 'definition' },
    { q: 'You can buy small presents here.', o: ['a spa', 'a gift shop', 'a lift'], a: 1,
        e: 'A gift shop sells presents.', c: 'definition' },
    { q: 'You use this to dry yourself after a shower.', o: ['a pillow', 'a towel', 'a cupboard'], a: 1,
        e: 'You dry yourself with a towel.', c: 'definition' },
    { q: 'You put your clothes in this.', o: ['a cupboard', 'a table', 'a floor'], a: 0,
        e: 'Clothes go in a cupboard.', c: 'definition' },
    { q: 'You can swim here.', o: ['a bar', 'a swimming pool', 'a garden'], a: 1,
        e: 'You swim in a swimming pool.', c: 'definition' },
    { q: 'It is next to the bed and it gives you light.', o: ['a lamp', 'a chair', 'a window'], a: 0,
        e: 'A lamp gives light next to the bed.', c: 'definition' },
    { q: 'You can have a drink here, but not a big dinner.', o: ['a bar', 'a factory', 'a school'], a: 0,
        e: 'A bar is for drinks.', c: 'definition' },
    { q: 'It is the floor of a building at street level.', o: ['the third floor', 'the ground floor', 'the fifth floor'],
        a: 1, e: 'The ground floor is at street level.', c: 'definition', d: 3 },
    { q: 'You need this to use the internet in your room.', o: ['a remote control', 'wi-fi', 'a lift'], a: 1,
        e: 'Wi-fi gives you the internet.', c: 'definition' },
    // --- odd one out ---------------------------------------------------------------
    { q: 'Which word is different? a restaurant', o: ['reception', 'a gift shop', 'a pillow'], a: 2,
        e: 'A restaurant, reception and a gift shop are places in a hotel. A pillow is an object in a room.',
        c: 'odd-one-out', d: 3 },
    { q: 'Which word is different? a shower', o: ['a toilet', 'a garden', 'a bath'], a: 1,
        e: 'A shower, a toilet and a bath are in the bathroom. A garden is outside.',
        c: 'odd-one-out', d: 3 },
    { q: 'Which word is different? a light', o: ['a lamp', 'a towel', 'a remote control'], a: 1,
        e: 'A light, a lamp and a remote control all use electricity. A towel does not.',
        c: 'odd-one-out', d: 3 },
    { q: 'Which word is different? a cupboard', o: ['a table', 'a chair', 'the floor'], a: 2,
        e: 'A cupboard, a table and a chair are furniture. The floor is part of the room.',
        c: 'odd-one-out', d: 3 },
    { q: 'Which word is different? a museum', o: ['a park', 'a street', 'a lift'], a: 2,
        e: 'A museum, a park and a street are places in a town. A lift is inside a building.',
        c: 'odd-one-out', d: 3 },
    { q: 'Which word is different? a bed', o: ['a pillow', 'a spa', 'a lamp'], a: 1,
        e: 'A bed, a pillow and a lamp are in a hotel room. A spa is a place in the hotel.',
        c: 'odd-one-out', d: 3 },
    { q: 'Which word is different? a gym', o: ['a swimming pool', 'a towel', 'a spa'], a: 1,
        e: 'A gym, a swimming pool and a spa are places in a hotel. A towel is an object.',
        c: 'odd-one-out', d: 3 },
    { q: 'Which word is different? a waiter', o: ['a receptionist', 'a doctor', 'a restaurant'], a: 2,
        e: 'A waiter, a receptionist and a doctor are jobs. A restaurant is a place.',
        c: 'odd-one-out', d: 3 },
    // --- hotel sentences ---------------------------------------------------------------
    { q: 'Our room has a beautiful ___ of the mountains.', o: ['view', 'floor', 'lift'], a: 0,
        e: 'You have a view of something from a window.', c: 'sentence' },
    { q: 'I’d like a ___ room for two people, please.', o: ['single', 'double', 'ground'], a: 1,
        e: 'A double room is for two people.', c: 'sentence' },
    { q: 'There aren’t any ___ in the bathroom. Can you bring some?', o: ['towels', 'lifts', 'gardens'], a: 0,
        e: 'Towels belong in the bathroom.', c: 'sentence' },
    { q: 'The hotel has a big ___ with trees and flowers.', o: ['garden', 'bathroom', 'cupboard'], a: 0,
        e: 'A garden has trees and flowers.', c: 'sentence' },
];
export const vocabHotels = makeQuestions({
    topicId: 'beg-v-hotels',
    categoryId: 'vocabulary',
    unit: 10,
    type: 'choose-word',
    source: SRC,
    slug: 'ho',
}, drafts);
