import { makeQuestions } from './build';
const VB = (page, ref) => ({ book: 'SB', page, ref });
const datesDrafts = [
    { q: 'What comes after Friday?', o: ['Thursday', 'Saturday', 'Monday'], a: 1,
        e: 'Saturday follows Friday.', c: 'days', d: 1 },
    { q: 'Which day comes before Wednesday?', o: ['Tuesday', 'Thursday', 'Sunday'], a: 0,
        e: 'Tuesday comes before Wednesday.', c: 'days', d: 1 },
    { q: 'Which month is the last month of the year?', o: ['November', 'December', 'January'], a: 1,
        e: 'December is the last month.', c: 'months', d: 1 },
    { q: 'Which month comes before May?', o: ['April', 'June', 'March'], a: 0,
        e: 'April comes before May.', c: 'months' },
    { q: 'How many months are there in a year?', o: ['ten', 'twelve', 'seven'], a: 1,
        e: 'There are twelve months.', c: 'months', d: 1 },
    { q: 'How many days are there in a week?', o: ['seven', 'five', 'twelve'], a: 0,
        e: 'There are seven days in a week.', c: 'days', d: 1 },
    { q: 'How do we say 21st?', o: ['twenty-one', 'twenty-first', 'twentieth-one'], a: 1,
        e: '21st is twenty-first.', c: 'ordinals', d: 3 },
    { q: 'How do we say 30th?', o: ['thirty', 'thirtieth', 'thirtyth'], a: 1,
        e: '30th is thirtieth.', c: 'ordinals', d: 3 },
];
const timeDrafts = [
    { q: 'What time is 3.00?', o: ['three o’clock', 'three past', 'half three'], a: 0,
        e: 'A whole hour is o’clock.', c: 'clock', d: 1 },
    { q: 'What time is 6.30?', o: ['half to seven', 'half past six', 'six past half'], a: 1,
        e: '6.30 is half past six.', c: 'clock' },
    { q: 'What time is 10.15?', o: ['a quarter past ten', 'a quarter to ten', 'half past ten'], a: 0,
        e: '10.15 is a quarter past ten.', c: 'clock' },
    { q: 'What time is 8.45?', o: ['a quarter past eight', 'a quarter to nine', 'a quarter to eight'], a: 1,
        e: '8.45 is a quarter to nine, because it is fifteen minutes before nine.', c: 'clock', d: 3 },
    { q: 'A quarter to seven is ___.', o: ['7.15', '6.45', '7.45'], a: 1,
        e: 'A quarter to seven is 6.45.', c: 'clock', d: 3 },
    { q: '___ time do you get up?', o: ['Which', 'What', 'How'], a: 1,
        e: 'We ask What time…?', c: 'asking' },
    { q: 'She gets up ___ a quarter to seven.', o: ['in', 'on', 'at'], a: 2,
        e: 'We use at with a clock time.', c: 'asking' },
];
const verbPhraseDrafts = [
    { q: 'I ___ in a flat in the centre of town.', o: ['live', 'stay', 'go'], a: 0,
        e: 'The book uses live in a flat.', c: 'phrases', d: 1 },
    { q: 'I ___ to the radio in the morning.', o: ['hear', 'listen', 'watch'], a: 1,
        e: 'We listen to the radio.', c: 'phrases', d: 3 },
    { q: 'I ___ TV in the evening.', o: ['listen', 'look', 'watch'], a: 2,
        e: 'We watch TV.', c: 'phrases', d: 3 },
    { q: 'I ___ the newspaper every morning.', o: ['read', 'watch', 'listen'], a: 0,
        e: 'We read a newspaper.', c: 'phrases' },
    { q: 'I ___ English and a little Spanish.', o: ['say', 'speak', 'tell'], a: 1,
        e: 'We speak a language.', c: 'phrases' },
    { q: 'I ___ in a bank in the city.', o: ['work', 'do', 'make'], a: 0,
        e: 'We work in a bank.', c: 'phrases' },
    { q: 'I ___ fast food, but not often.', o: ['drink', 'eat', 'have a'], a: 1,
        e: 'We eat food.', c: 'phrases' },
    { q: 'I ___ a new car.', o: ['need', 'do', 'go'], a: 0,
        e: 'Need means you must have something.', c: 'phrases' },
    { q: 'I ___ to English classes twice a week.', o: ['go', 'do', 'make'], a: 0,
        e: 'The book uses go to English classes.', c: 'phrases' },
    { q: 'I ___ a dog and two cats.', o: ['am', 'have', 'do'], a: 1,
        e: 'We have a pet.', c: 'phrases', d: 1 },
];
const filmDrafts = [
    { q: 'A film with a lot of fighting and fast cars is an ___ film.', o: ['action', 'animated', 'romantic'], a: 0,
        e: 'An action film is fast and exciting.', c: 'kinds' },
    { q: 'A film about love is a ___ film.', o: ['horror', 'romantic', 'western'], a: 1,
        e: 'A romantic film is about love.', c: 'kinds' },
    { q: 'A serious film about people’s lives is a ___.', o: ['comedy', 'musical', 'drama'], a: 2,
        e: 'A drama is serious.', c: 'kinds' },
    { q: 'A film about the future and space is a ___ film.', o: ['science fiction', 'western', 'horror'], a: 0,
        e: 'Science fiction is about the future.', c: 'kinds' },
    { q: 'Which word is different? a comedy', o: ['a drama', 'a western', 'a cinema'], a: 2,
        e: 'A comedy, a drama and a western are kinds of film. A cinema is a place.',
        c: 'kinds', d: 3 },
    { q: 'We go to the ___ to see a film.', o: ['theatre', 'cinema', 'museum'], a: 1,
        e: 'We see films at the cinema.', c: 'kinds', d: 1 },
];
const activityDrafts = [
    { q: 'You sleep in a tent when you go ___.', o: ['camping', 'cycling', 'shopping'], a: 0,
        e: 'Camping means sleeping outside in a tent.', c: 'activities' },
    { q: 'You make food in the kitchen. This is ___.', o: ['cooking', 'cleaning', 'painting'], a: 0,
        e: 'Cooking is making food.', c: 'activities', d: 1 },
    { q: 'You use a bicycle. This is ___.', o: ['running', 'cycling', 'swimming'], a: 1,
        e: 'Cycling means riding a bicycle.', c: 'activities' },
    { q: 'You have dinner in a restaurant. This is ___.', o: ['eating out', 'cooking', 'shopping'], a: 0,
        e: 'Eating out means having a meal in a restaurant.', c: 'activities', d: 3 },
    { q: 'You are in a plane. This is ___.', o: ['travelling', 'flying', 'walking'], a: 1,
        e: 'Flying means travelling by plane.', c: 'activities' },
    { q: 'You use a brush and colours. This is ___.', o: ['reading', 'painting', 'singing'], a: 1,
        e: 'Painting uses a brush and colours.', c: 'activities' },
    { q: 'Which word is different? swimming', o: ['running', 'cycling', 'sleeping'], a: 2,
        e: 'Swimming, running and cycling are sport. Sleeping is not.', c: 'activities', d: 3 },
    { q: 'You go to the shops to buy clothes. This is ___.', o: ['shopping', 'camping', 'reading'], a: 0,
        e: 'Shopping means buying things.', c: 'activities', d: 1 },
];
const clothesDrafts = [
    { q: 'You wear this when it is cold outside.', o: ['a coat', 'shorts', 'a T-shirt'], a: 0,
        e: 'A coat keeps you warm.', c: 'clothes', d: 1 },
    { q: 'A woman sometimes wears this instead of trousers.', o: ['a shirt', 'a skirt', 'a cap'], a: 1,
        e: 'A skirt is worn instead of trousers.', c: 'clothes' },
    { q: 'You wear these under your shoes.', o: ['socks', 'jeans', 'hats'], a: 0,
        e: 'Socks go on your feet inside your shoes.', c: 'clothes' },
    { q: 'Which word is different? shoes', o: ['trainers', 'socks', 'a hat'], a: 2,
        e: 'Shoes, trainers and socks go on your feet. A hat goes on your head.',
        c: 'clothes', d: 3 },
    { q: 'You wear this on your head.', o: ['a cap', 'a jacket', 'a dress'], a: 0,
        e: 'A cap goes on your head.', c: 'clothes', d: 1 },
    { q: 'What ___ she wearing today?', o: ['is', 'does', 'has'], a: 0,
        e: 'The present continuous uses be: What is she wearing?', c: 'clothes', d: 3 },
    { q: 'Blue trousers made of strong material are ___.', o: ['shorts', 'jeans', 'a suit'], a: 1,
        e: 'Jeans are blue trousers.', c: 'clothes' },
];
const cfg = (topicId, unit, slug, page, ref) => ({ topicId, categoryId: 'vocabulary', unit, type: 'choose-word', source: VB(page, ref), slug });
export const vocabDates = makeQuestions(cfg('beg-v-days-months-dates', 1, 'dm', 127, 'Vocabulary Bank — Months and ordinal numbers'), datesDrafts);
export const vocabTime = makeQuestions(cfg('beg-v-the-time', 5, 'ti', 34, 'Practical English 3 — telling the time'), timeDrafts);
export const vocabVerbPhrases = makeQuestions(cfg('beg-v-verb-phrases-1', 5, 'vp', 123, 'Vocabulary Bank — Common verb phrases 1'), verbPhraseDrafts);
export const vocabFilms = makeQuestions(cfg('beg-v-films', 7, 'fi', 44, 'File 7B — kinds of films'), filmDrafts);
export const vocabActivities = makeQuestions(cfg('beg-v-activities', 8, 'ac', 128, 'Vocabulary Bank — Activities'), activityDrafts);
export const vocabClothes = makeQuestions(cfg('beg-v-clothes', 9, 'cw', 129, 'Vocabulary Bank — Clothes'), clothesDrafts);
