import { makeWords, type WordGroup } from '../build';
import type { VocabWord } from '../../../types';

/** Numbers, dates and countries — Vocabulary Bank SB pp.116-118. */
const groups: WordGroup[] = [
  {
    topicId: 'beg-v-numbers',
    unit: 1,
    rows: [
      ['zero', 'ноль', 'ear'],
      ['one', 'один', 'up', '/wʌn/'],
      ['two', 'два'],
      ['three', 'три'],
      ['four', 'четыре'],
      ['five', 'пять', 'bike', '/faɪv/'],
      ['six', 'шесть'],
      ['seven', 'семь'],
      ['eight', 'восемь'],
      ['nine', 'девять', 'bike'],
      ['ten', 'десять'],
      ['eleven', 'одиннадцать', 'egg'],
      ['twelve', 'двенадцать', 'egg', '/twelv/'],
      ['thirteen', 'тринадцать', 'tree', '/ˌθɜːˈtiːn/'],
      ['fourteen', 'четырнадцать', 'tree', '/ˌfɔːˈtiːn/'],
      ['fifteen', 'пятнадцать', 'tree'],
      ['sixteen', 'шестнадцать', 'tree', '/ˌsɪksˈtiːn/'],
      ['seventeen', 'семнадцать', 'tree', '/ˌsevnˈtiːn/'],
      ['eighteen', 'восемнадцать', 'tree', '/ˌeɪˈtiːn/'],
      ['nineteen', 'девятнадцать', 'tree', '/ˌnaɪnˈtiːn/'],
      ['twenty', 'двадцать'],
      ['thirty', 'тридцать', 'bird', '/ˈθɜːti/'],
      ['forty', 'сорок', 'horse', '/ˈfɔːti/'],
      ['fifty', 'пятьдесят', 'fish', '/ˈfɪfti/'],
      ['sixty', 'шестьдесят', 'fish', '/ˈsɪksti/'],
      ['seventy', 'семьдесят', 'egg', '/ˈsevnti/'],
      ['eighty', 'восемьдесят', 'train', '/ˈeɪti/'],
      ['ninety', 'девяносто', 'bike', '/ˈnaɪnti/'],
      ['hundred', 'сто', 'up', '/ˈhʌndrəd/'],
      ['number', 'номер, число'],
    ],
  },
  {
    topicId: 'beg-v-days-months-dates',
    unit: 1,
    rows: [
      ['Monday', 'понедельник', 'up', '/ˈmʌndeɪ/'],
      ['Tuesday', 'вторник', 'boot', '/ˈtjuːzdeɪ/'],
      ['Wednesday', 'среда', 'egg', '/ˈwenzdeɪ/'],
      ['Thursday', 'четверг', 'bird'],
      ['Friday', 'пятница', 'bike', '/ˈfraɪdeɪ/'],
      ['Saturday', 'суббота', 'cat', '/ˈsætədeɪ/'],
      ['Sunday', 'воскресенье', 'up', '/ˈsʌndeɪ/'],
      ['January', 'январь', 'cat', '/ˈdʒænjuəri/'],
      ['February', 'февраль', 'egg', '/ˈfebruəri/'],
      ['March', 'март', 'car', '/mɑːtʃ/'],
      ['April', 'апрель', 'train', '/ˈeɪprəl/'],
      ['May', 'май', 'train', '/meɪ/'],
      ['June', 'июнь', 'boot', '/dʒuːn/'],
      ['July', 'июль', 'bike', '/dʒuˈlaɪ/'],
      ['August', 'август', 'horse', '/ˈɔːgəst/'],
      ['September', 'сентябрь', 'egg'],
      ['October', 'октябрь', 'phone'],
      ['November', 'ноябрь', 'egg'],
      ['December', 'декабрь', 'egg'],
      ['day', 'день'],
      ['week', 'неделя', 'tree', '/wiːk/'],
      ['weekend', 'выходные', 'egg', '/ˌwiːkˈend/'],
      ['month', 'месяц', 'up'],
      ['year', 'год'],
      ['today', 'сегодня', 'train', '/təˈdeɪ/'],
      ['tomorrow', 'завтра', 'clock'],
      ['yesterday', 'вчера', 'egg'],
      ['birthday', 'день рождения', 'bird'],
      ['first', 'первый', 'bird', '/fɜːst/'],
      ['second', 'второй', 'egg', '/ˈsekənd/'],
      ['third', 'третий', 'bird', '/θɜːd/'],
      ['fourth', 'четвёртый', 'horse', '/fɔːθ/'],
      ['fifth', 'пятый', 'fish', '/fɪfθ/'],
      ['twelfth', 'двенадцатый', 'egg', '/twelfθ/'],
      ['twentieth', 'двадцатый', 'egg', '/ˈtwentiəθ/'],
    ],
  },
  {
    topicId: 'beg-v-countries-nationalities',
    unit: 2,
    rows: [
      ['England', 'Англия', 'fish', '/ˈɪŋglənd/'],
      ['English', 'английский'],
      ['France', 'Франция', 'car', '/frɑːns/'],
      ['French', 'французский', 'egg', '/frentʃ/'],
      ['Germany', 'Германия', 'bird', '/ˈdʒɜːməni/'],
      ['German', 'немецкий', 'bird', '/ˈdʒɜːmən/'],
      ['Italy', 'Италия'],
      ['Italian', 'итальянский', 'cat', '/ɪˈtæliən/'],
      ['Spain', 'Испания'],
      ['Spanish', 'испанский', 'cat'],
      ['Poland', 'Польша', 'phone'],
      ['Polish', 'польский', 'phone', '/ˈpəʊlɪʃ/'],
      ['Russia', 'Россия', 'up', '/ˈrʌʃə/'],
      ['Russian', 'русский', 'up', '/ˈrʌʃn/'],
      ['Turkey', 'Турция'],
      ['Turkish', 'турецкий', 'bird', '/ˈtɜːkɪʃ/'],
      ['Japan', 'Япония', 'cat'],
      ['Japanese', 'японский', 'tree', '/ˌdʒæpəˈniːz/'],
      ['China', 'Китай', 'bike', '/ˈtʃaɪnə/'],
      ['Chinese', 'китайский', 'tree', '/ˌtʃaɪˈniːz/'],
      ['Brazil', 'Бразилия', 'fish'],
      ['Brazilian', 'бразильский', 'fish'],
      ['Mexico', 'Мексика'],
      ['Mexican', 'мексиканский', 'egg', '/ˈmeksɪkən/'],
      ['Egypt', 'Египет', 'tree', '/ˈiːdʒɪpt/'],
      ['Egyptian', 'египетский', 'fish', '/ɪˈdʒɪpʃn/'],
      ['America', 'Америка', 'egg', '/əˈmerɪkə/'],
      ['American', 'американский', 'egg', '/əˈmerɪkən/'],
      ['British', 'британский', 'fish'],
      ['country', 'страна', 'up', '/ˈkʌntri/'],
      ['nationality', 'национальность', 'cat', '/ˌnæʃəˈnæləti/'],
      ['language', 'язык', 'cat', '/ˈlæŋgwɪdʒ/'],
    ],
  },
];

export const basicsWords: VocabWord[] = makeWords(groups);
