import { makeWords, type WordGroup } from '../build';
import type { VocabWord } from '../../../types';

/** The classroom and small everyday things — Vocabulary Bank SB pp.116, 119. */
const groups: WordGroup[] = [
  {
    topicId: 'beg-v-classroom',
    unit: 1,
    rows: [
      ['board', 'доска', 'horse', '/bɔːd/'],
      ['door', 'дверь'],
      ['window', 'окно'],
      ['chair', 'стул'],
      ['table', 'стол', 'train', '/ˈteɪbl/'],
      ['laptop', 'ноутбук', 'cat', '/ˈlæptɒp/'],
      ['dictionary', 'словарь', 'fish'],
      ['paper', 'бумага', 'train'],
      ['pen', 'ручка', 'egg', '/pen/'],
      ['pencil', 'карандаш', 'egg', '/ˈpensl/'],
      ['bag', 'сумка'],
      ['book', 'книга'],
      ['notebook', 'тетрадь', 'phone', '/ˈnəʊtbʊk/'],
      ['page', 'страница', 'train', '/peɪdʒ/'],
      ['coat', 'пальто'],
      ['phone', 'телефон', 'phone'],
      ['teacher', 'учитель', 'tree', '/ˈtiːtʃə/'],
      ['student', 'студент', 'boot', '/ˈstjuːdnt/'],
      ['class', 'урок, класс', 'car', '/klɑːs/'],
      ['classroom', 'класс, аудитория', 'car', '/ˈklɑːsruːm/'],
      ['room', 'комната', 'boot', '/ruːm/'],
      ['wall', 'стена', 'horse', '/wɔːl/'],
      ['open', 'открывать'],
      ['close', 'закрывать'],
      ['listen', 'слушать', 'fish', '/ˈlɪsn/'],
      ['read', 'читать'],
      ['write', 'писать', 'bike', '/raɪt/'],
      ['spell', 'произносить по буквам'],
      ['understand', 'понимать', 'cat', '/ˌʌndəˈstænd/'],
      ['repeat', 'повторить', 'tree', '/rɪˈpiːt/'],
      ['sit', 'сидеть', 'fish'],
      ['stand', 'стоять', 'cat'],
      ['answer', 'ответ, отвечать', 'car', '/ˈɑːnsə/'],
      ['question', 'вопрос', 'egg', '/ˈkwestʃən/'],
      ['sentence', 'предложение', 'egg', '/ˈsentəns/'],
      ['word', 'слово'],
      ['letter', 'буква, письмо', 'egg', '/ˈletə/'],
      ['please', 'пожалуйста'],
      ['sorry', 'извините'],
      ['hello', 'здравствуйте'],
      ['goodbye', 'до свидания', 'bike', '/ˌgʊdˈbaɪ/'],
      ['thanks', 'спасибо'],
    ],
  },
  {
    topicId: 'beg-v-small-things',
    unit: 3,
    rows: [
      ['wallet', 'бумажник', 'clock', '/ˈwɒlɪt/'],
      ['purse', 'кошелёк', 'bird', '/pɜːs/'],
      ['key', 'ключ'],
      ['watch', 'часы (наручные)'],
      ['mobile', 'мобильный телефон', 'phone', '/ˈməʊbaɪl/'],
      ['tablet', 'планшет', 'cat', '/ˈtæblət/'],
      ['glasses', 'очки', 'car', '/ˈglɑːsɪz/'],
      ['photo', 'фотография'],
      ['camera', 'фотоаппарат', 'cat', '/ˈkæmərə/'],
      ['charger', 'зарядное устройство', 'car', '/ˈtʃɑːdʒə/'],
      ['card', 'карта, карточка', 'car', '/kɑːd/'],
      ['credit', 'кредит', 'egg'],
      ['passport', 'паспорт', 'car', '/ˈpɑːspɔːt/'],
      ['umbrella', 'зонт'],
      ['newspaper', 'газета', 'boot'],
      ['money', 'деньги', 'up', '/ˈmʌni/'],
    ],
  },
];

export const classroomWords: VocabWord[] = makeWords(groups);
