import { makeWords, type WordGroup } from '../build';
import type { VocabWord } from '../../../types';

/** Food, the time and common verb phrases — Vocabulary Bank SB pp.122-123. */
const groups: WordGroup[] = [
  {
    topicId: 'beg-v-food-drink',
    unit: 5,
    rows: [
      ['fish', 'рыба', 'fish', '/fɪʃ/'],
      ['meat', 'мясо', 'tree', '/miːt/'],
      ['pasta', 'паста, макароны', 'cat', '/ˈpæstə/'],
      ['rice', 'рис', 'bike', '/raɪs/'],
      ['eggs', 'яйца', 'egg'],
      ['yogurt', 'йогурт', 'clock', '/ˈjɒgət/'],
      ['vegetables', 'овощи', 'egg'],
      ['potatoes', 'картофель', 'train'],
      ['carrots', 'морковь', 'cat', '/ˈkærəts/'],
      ['salad', 'салат', 'cat', '/ˈsæləd/'],
      ['fruit', 'фрукты', 'boot', '/fruːt/'],
      ['bread', 'хлеб'],
      ['butter', 'масло', 'up', '/ˈbʌtə/'],
      ['cheese', 'сыр'],
      ['sugar', 'сахар'],
      ['salt', 'соль', 'horse', '/sɔːlt/'],
      ['sandwich', 'бутерброд', 'cat', '/ˈsænwɪdʒ/'],
      ['cereal', 'хлопья, каша'],
      ['chocolate', 'шоколад', 'clock', '/ˈtʃɒklət/'],
      ['coffee', 'кофе'],
      ['tea', 'чай', 'tree', '/tiː/'],
      ['milk', 'молоко', 'fish', '/mɪlk/'],
      ['water', 'вода'],
      ['juice', 'сок'],
      ['wine', 'вино', 'bike', '/waɪn/'],
      ['beer', 'пиво'],
      ['breakfast', 'завтрак'],
      ['lunch', 'обед', 'up'],
      ['dinner', 'ужин', 'fish'],
      ['food', 'еда'],
      ['drink', 'напиток, пить', 'fish', '/drɪŋk/'],
      ['eat', 'есть, кушать', 'tree', '/iːt/'],
      ['meal', 'приём пищи', 'tree', '/miːl/'],
    ],
  },
  {
    topicId: 'beg-v-the-time',
    unit: 5,
    rows: [
      ['time', 'время', 'bike'],
      ["o'clock", 'часов (ровно)', 'clock', '/əˈklɒk/'],
      ['quarter', 'четверть', 'horse', '/ˈkwɔːtə/'],
      ['half', 'половина', 'car', '/hɑːf/'],
      ['past', 'после (о времени)', 'car', '/pɑːst/'],
      ['hour', 'час', 'owl', '/ˈaʊə/'],
      ['minutes', 'минуты', 'fish', '/ˈmɪnɪts/'],
      ['morning', 'утро', 'horse', '/ˈmɔːnɪŋ/'],
      ['afternoon', 'день, время после полудня'],
      ['evening', 'вечер', 'tree', '/ˈiːvnɪŋ/'],
      ['night', 'ночь'],
    ],
  },
  {
    topicId: 'beg-v-verb-phrases-1',
    unit: 5,
    rows: [
      ['live', 'жить', 'fish'],
      ['have', 'иметь', 'cat'],
      ['work', 'работать'],
      ['study', 'учиться', 'up', '/ˈstʌdi/'],
      ['go', 'идти, ехать'],
      ['want', 'хотеть'],
      ['need', 'нуждаться', 'tree', '/niːd/'],
      ['like', 'нравиться', 'bike', '/laɪk/'],
      ['love', 'любить', 'up', '/lʌv/'],
      ['hate', 'ненавидеть', 'train', '/heɪt/'],
      ['speak', 'говорить', 'tree', '/spiːk/'],
      ['play', 'играть', 'train', '/pleɪ/'],
      ['meet', 'встречать'],
      ['travel', 'путешествовать', 'cat', '/ˈtrævl/'],
      ['walk', 'идти пешком', 'horse', '/wɔːk/'],
      ['get', 'получать, становиться', 'egg', '/get/'],
      ['buy', 'покупать'],
      ['make', 'делать', 'train', '/meɪk/'],
      ['take', 'брать', 'train', '/teɪk/'],
      ['give', 'давать', 'fish', '/gɪv/'],
      ['say', 'сказать'],
      ['tell', 'рассказать', 'egg'],
      ['see', 'видеть', 'tree', '/siː/'],
      ['know', 'знать', 'phone', '/nəʊ/'],
      ['think', 'думать', 'fish'],
      ['help', 'помогать', 'egg', '/help/'],
      ['ask', 'спрашивать', 'car', '/ɑːsk/'],
      ['start', 'начинать', 'car', '/stɑːt/'],
      ['finish', 'заканчивать', 'fish'],
      ['stop', 'останавливать'],
      ['use', 'использовать', 'boot', '/juːz/'],
      ['flat', 'квартира', 'cat', '/flæt/'],
      ['home', 'дом', 'phone', '/həʊm/'],
      ['radio', 'радио', 'train', '/ˈreɪdiəʊ/'],
    ],
  },
];

export const foodWords: VocabWord[] = makeWords(groups);
