import { makeWords, type WordGroup } from '../build';
import type { VocabWord } from '../../../types';

/** People, family, colours and common adjectives — Vocabulary Bank SB pp.120-121. */
const groups: WordGroup[] = [
  {
    topicId: 'beg-v-people-family',
    unit: 4,
    rows: [
      ['man', 'мужчина'],
      ['men', 'мужчины', 'egg'],
      ['woman', 'женщина'],
      ['women', 'женщины'],
      ['boy', 'мальчик', 'boy', '/bɔɪ/'],
      ['girl', 'девочка'],
      ['child', 'ребёнок', 'bike', '/tʃaɪld/'],
      ['children', 'дети', 'fish'],
      ['person', 'человек'],
      ['people', 'люди'],
      ['friend', 'друг'],
      ['family', 'семья', 'cat'],
      ['mother', 'мать'],
      ['father', 'отец'],
      ['sister', 'сестра', 'fish', '/ˈsɪstə/'],
      ['brother', 'брат'],
      ['son', 'сын'],
      ['daughter', 'дочь', 'horse', '/ˈdɔːtə/'],
      ['husband', 'муж'],
      ['wife', 'жена'],
      ['parents', 'родители', 'chair', '/ˈpeərənts/'],
      ['grandmother', 'бабушка', 'cat'],
      ['grandfather', 'дедушка', 'cat'],
      ['grandparents', 'бабушка и дедушка', 'cat', '/ˈgrænpeərənts/'],
      ['boyfriend', 'парень, молодой человек'],
      ['girlfriend', 'девушка', 'bird', '/ˈgɜːlfrend/'],
    ],
  },
  {
    topicId: 'beg-v-colours-adjectives',
    unit: 4,
    rows: [
      ['colour', 'цвет', 'up'],
      ['black', 'чёрный'],
      ['blue', 'синий'],
      ['brown', 'коричневый'],
      ['green', 'зелёный', 'tree'],
      ['grey', 'серый'],
      ['orange', 'оранжевый', 'clock', '/ˈɒrɪndʒ/'],
      ['pink', 'розовый', 'fish', '/pɪŋk/'],
      ['red', 'красный'],
      ['white', 'белый'],
      ['yellow', 'жёлтый', 'egg'],
      ['big', 'большой', 'fish'],
      ['small', 'маленький', 'horse', '/smɔːl/'],
      ['old', 'старый'],
      ['new', 'новый'],
      ['fast', 'быстрый'],
      ['slow', 'медленный', 'phone', '/sləʊ/'],
      ['beautiful', 'красивый'],
      ['ugly', 'некрасивый', 'up', '/ˈʌgli/'],
      ['cheap', 'дешёвый', 'tree', '/tʃiːp/'],
      ['expensive', 'дорогой', 'egg'],
      ['long', 'длинный', 'clock', '/lɒŋ/'],
      ['short', 'короткий'],
      ['clean', 'чистый', 'tree', '/kliːn/'],
      ['dirty', 'грязный', 'bird', '/ˈdɜːti/'],
      ['easy', 'лёгкий', 'tree'],
      ['difficult', 'трудный', 'fish'],
      ['tall', 'высокий'],
      ['good', 'хороший'],
      ['bad', 'плохой'],
      ['great', 'отличный'],
      ['fantastic', 'потрясающий', 'cat', '/fænˈtæstɪk/'],
      ['awful', 'ужасный', 'horse', '/ˈɔːfl/'],
      ['terrible', 'ужасный', 'egg', '/ˈterəbl/'],
      ['nice', 'милый, приятный'],
      ['perfect', 'идеальный', 'bird', '/ˈpɜːfɪkt/'],
      ['famous', 'известный', 'train', '/ˈfeɪməs/'],
      ['fine', 'хорошо, отлично', 'bike'],
      ['hot', 'горячий', 'clock', '/hɒt/'],
      ['cold', 'холодный', 'phone', '/kəʊld/'],
      ['late', 'поздний'],
      ['early', 'ранний', 'bird', '/ˈɜːli/'],
      ['tired', 'уставший', 'bike', '/ˈtaɪəd/'],
      ['thirsty', 'испытывающий жажду'],
      ['hungry', 'голодный', 'up', '/ˈhʌŋgri/'],
      ['happy', 'счастливый', 'cat', '/ˈhæpi/'],
      ['angry', 'сердитый', 'cat', '/ˈæŋgri/'],
      ['young', 'молодой'],
    ],
  },
];

export const peopleWords: VocabWord[] = makeWords(groups);
