import { makeWords, type WordGroup } from '../build';
import type { VocabWord } from '../../../types';

/** "Words and phrases to learn", SB p.132 — lessons 7A to 12A. */
const groups: WordGroup[] = [
  {
    topicId: 'beg-v-words-to-learn',
    unit: 7,
    rows: [
      ['cent', 'цент', 'egg', '/sent/'],
      ['same', 'тот же, одинаковый', 'train', '/seɪm/'],
      ['fun', 'веселье; весёлый', 'up', '/fʌn/'],
      ['exciting', 'захватывающий', 'bike', '/ɪkˈsaɪtɪŋ/'],
      ['pub', 'паб', 'up', '/pʌb/'],
      ['fan', 'болельщик, фанат', 'cat', '/fæn/'],
      ['depend', 'зависеть', 'egg', '/dɪˈpend/'],
      ['more', 'больше', 'horse', '/mɔː/'],
      ['less', 'меньше', 'egg', '/les/'],
      ['except', 'кроме', 'egg', '/ɪkˈsept/'],
      ['definitely', 'определённо, точно', 'egg', '/ˈdefɪnətli/'],
      ['director', 'режиссёр, директор', 'egg', '/dəˈrektə/'],
      ['scene', 'сцена', 'tree', '/siːn/'],
      ['kiss', 'поцелуй; целовать', 'fish', '/kɪs/'],
      ['quiet', 'тихий', 'bike', '/ˈkwaɪət/'],
      ['cry', 'плакать', 'bike', '/kraɪ/'],
      ['move', 'двигаться, переезжать', 'boot', '/muːv/'],
      ['anything', 'что-нибудь, ничего', 'egg', '/ˈeniθɪŋ/'],
      ['about', 'о, про; около', 'computer', '/əˈbaʊt/'],
      ['nothing', 'ничего', 'up', '/ˈnʌθɪŋ/'],
    ],
  },
  {
    topicId: 'beg-v-words-to-learn',
    unit: 8,
    rows: [
      ['licence', 'права, лицензия', 'bike', '/ˈlaɪsns/'],
      ['theory', 'теория', 'ear', '/ˈθɪəri/'],
      ['test', 'тест, экзамен', 'egg', '/test/'],
      ['practical', 'практический', 'cat', '/ˈpræktɪkl/'],
      ['instructor', 'инструктор', 'up', '/ɪnˈstrʌktə/'],
      ['drive', 'водить машину', 'bike', '/draɪv/'],
      ['fail', 'провалить, не сдать', 'train', '/feɪl/'],
      ['nervous', 'нервный, волнующийся', 'bird', '/ˈnɜːvəs/'],
      ['total', 'полный, общий', 'phone', '/ˈtəʊtl/'],
      ['disaster', 'катастрофа', 'car', '/dɪˈzɑːstə/'],
      ['course', 'курс', 'horse', '/kɔːs/'],
      ['horrible', 'ужасный', 'clock', '/ˈhɒrəbl/'],
      ['peaceful', 'спокойный, мирный', 'tree', '/ˈpiːsfl/'],
      ['frightened', 'испуганный', 'bike', '/ˈfraɪtnd/'],
      ['alone', 'один, в одиночестве', 'phone', '/əˈləʊn/'],
      ['concentrate', 'сосредоточиться', 'clock', '/ˈkɒnsntreɪt/'],
      ['loudly', 'громко', 'owl', '/ˈlaʊdli/'],
    ],
  },
  {
    topicId: 'beg-v-words-to-learn',
    unit: 9,
    rows: [
      ['living', 'жилой; жизнь', 'fish', '/ˈlɪvɪŋ/'],
      ['box', 'коробка', 'clock', '/bɒks/'],
      ['darling', 'дорогой, милый', 'car', '/ˈdɑːlɪŋ/'],
      ['towards', 'к, в сторону', 'horse', '/təˈwɔːdz/'],
      ['outside', 'снаружи, на улице', 'bike', '/ˌaʊtˈsaɪd/'],
      ['boss', 'начальник', 'clock', '/bɒs/'],
      ['experience', 'опыт', 'ear', '/ɪkˈspɪəriəns/'],
      ['serve', 'подавать, обслуживать', 'bird', '/sɜːv/'],
      ['hard', 'тяжело; твёрдый', 'car', '/hɑːd/'],
      ['broken', 'сломанный', 'phone', '/ˈbrəʊkən/'],
      ['surprised', 'удивлённый', 'bike', '/səˈpraɪzd/'],
    ],
  },
  {
    topicId: 'beg-v-words-to-learn',
    unit: 10,
    rows: [
      ['destination', 'место назначения', 'train', '/ˌdestɪˈneɪʃn/'],
      ['coast', 'побережье', 'phone', '/kəʊst/'],
      ['island', 'остров', 'bike', '/ˈaɪlənd/'],
      ['lake', 'озеро', 'train', '/leɪk/'],
      ['castle', 'замок', 'car', '/ˈkɑːsl/'],
      ['visitor', 'посетитель', 'fish', '/ˈvɪzɪtə/'],
      ['trip', 'поездка', 'fish', '/trɪp/'],
      ['boat', 'лодка, катер', 'phone', '/bəʊt/'],
      ['monster', 'чудовище', 'clock', '/ˈmɒnstə/'],
      ['tonight', 'сегодня вечером', 'bike', '/təˈnaɪt/'],
      ['stay', 'оставаться; пребывание', 'train', '/steɪ/'],
      ['robbery', 'ограбление', 'clock', '/ˈrɒbəri/'],
      ['suspect', 'подозреваемый', 'up', '/ˈsʌspekt/'],
      ['detective', 'детектив', 'egg', '/dɪˈtektɪv/'],
      ['last', 'прошлый; последний', 'car', '/lɑːst/'],
      ['secret', 'тайна; тайный', 'tree', '/ˈsiːkrət/'],
      ['strong', 'сильный', 'clock', '/strɒŋ/'],
      ['together', 'вместе', 'egg', '/təˈgeðə/'],
      ['century', 'век, столетие', 'egg', '/ˈsentʃəri/'],
      ['lock', 'замок (запор); запирать', 'clock', '/lɒk/'],
      ['store', 'склад; магазин', 'horse', '/stɔː/'],
      ['building', 'здание', 'fish', '/ˈbɪldɪŋ/'],
      ['luxury', 'роскошь; роскошный', 'up', '/ˈlʌkʃəri/'],
    ],
  },
  {
    topicId: 'beg-v-words-to-learn',
    unit: 11,
    rows: [
      ['designer', 'дизайнер', 'bike', '/dɪˈzaɪnə/'],
      ['national', 'национальный', 'cat', '/ˈnæʃnəl/'],
      ['public', 'общественный', 'up', '/ˈpʌblɪk/'],
      ['transport', 'транспорт', 'cat', '/ˈtrænspɔːt/'],
      ['trumpet', 'труба', 'up', '/ˈtrʌmpɪt/'],
      ['club', 'клуб', 'up', '/klʌb/'],
      ['blueberry', 'черника', 'boot', '/ˈbluːbəri/'],
      ['abroad', 'за границу', 'horse', '/əˈbrɔːd/'],
      ['organic', 'органический', 'cat', '/ɔːˈgænɪk/'],
      ['visit', 'посещать', 'fish', '/ˈvɪzɪt/'],
      ['pick', 'собирать, выбирать', 'fish', '/pɪk/'],
      ['return', 'возвращать(ся)', 'bird', '/rɪˈtɜːn/'],
      ['exam', 'экзамен', 'cat', '/ɪgˈzæm/'],
      ['eye', 'глаз', 'bike', '/aɪ/'],
      ['operation', 'операция', 'train', '/ˌɒpəˈreɪʃn/'],
      ['soldier', 'солдат', 'phone', '/ˈsəʊldʒə/'],
      ['special', 'особый', 'egg', '/ˈspeʃl/'],
      ['pretty', 'красивый; довольно', 'fish', '/ˈprɪti/'],
      ['shave', 'бриться', 'train', '/ʃeɪv/'],
      ['somebody', 'кто-то', 'up', '/ˈsʌmbədi/'],
      ['marry', 'жениться, выходить замуж', 'cat', '/ˈmæri/'],
    ],
  },
  {
    topicId: 'beg-v-words-to-learn',
    unit: 12,
    rows: [
      ['platform', 'платформа', 'cat', '/ˈplætfɔːm/'],
      ['smell', 'запах; пахнуть', 'egg', '/smel/'],
      ['classical', 'классический', 'cat', '/ˈklæsɪkl/'],
      ['message', 'сообщение', 'egg', '/ˈmesɪdʒ/'],
      ['hall', 'зал', 'horse', '/hɔːl/'],
      ['seat', 'место, сиденье', 'tree', '/siːt/'],
      ['exchange', 'обмен; обменивать', 'train', '/ɪksˈtʃeɪndʒ/'],
      ['interesting', 'интересный', 'fish', '/ˈɪntrəstɪŋ/'],
    ],
  },
];

export const toLearn7to12: VocabWord[] = makeWords(groups);
