import { makeWords, type WordGroup } from '../build';
import type { VocabWord } from '../../../types';

/** Travelling, clothes, hotels and prepositions — Vocabulary Bank SB pp.128-130. */
const groups: WordGroup[] = [
  {
    topicId: 'beg-v-travelling',
    unit: 9,
    rows: [
      ['tickets', 'билеты', 'fish', '/ˈtɪkɪts/'],
      ['suitcase', 'чемодан', 'boot', '/ˈsuːtkeɪs/'],
      ['pack', 'упаковывать', 'cat', '/pæk/'],
      ['leave', 'уезжать, покидать', 'tree', '/liːv/'],
      ['carry', 'нести', 'cat', '/ˈkæri/'],
      ['train', 'поезд', 'train', '/treɪn/'],
      ['bus', 'автобус', 'up', '/bʌs/'],
      ['plane', 'самолёт', 'train', '/pleɪn/'],
      ['flight', 'рейс, перелёт', 'bike', '/flaɪt/'],
      ['airport', 'аэропорт'],
      ['wait', 'ждать', 'train', '/weɪt/'],
      ['rent', 'брать напрокат', 'egg', '/rent/'],
      ['car', 'машина'],
      ['arrive', 'прибывать', 'bike', '/əˈraɪv/'],
      ['city', 'город', 'fish'],
      ['presents', 'подарки', 'egg', '/ˈpreznts/'],
    ],
  },
  {
    topicId: 'beg-v-clothes',
    unit: 9,
    rows: [
      ['clothes', 'одежда', 'phone', '/kləʊðz/'],
      ['sweater', 'свитер', 'egg', '/ˈswetə/'],
      ['t-shirt', 'футболка', 'tree', '/ˈtiːʃɜːt/'],
      ['shirt', 'рубашка'],
      ['trousers', 'брюки', 'owl', '/ˈtraʊzəz/'],
      ['jeans', 'джинсы', 'tree', '/dʒiːnz/'],
      ['shorts', 'шорты', 'horse', '/ʃɔːts/'],
      ['suit', 'костюм', 'boot', '/suːt/'],
      ['dress', 'платье', 'egg', '/dres/'],
      ['skirt', 'юбка'],
      ['jacket', 'куртка, пиджак', 'cat', '/ˈdʒækɪt/'],
      ['socks', 'носки', 'clock', '/sɒks/'],
      ['trainers', 'кроссовки', 'train', '/ˈtreɪnəz/'],
      ['shoes', 'туфли, обувь'],
      ['hat', 'шляпа'],
      ['cap', 'кепка'],
      ['sunglasses', 'солнцезащитные очки', 'up', '/ˈsʌnglɑːsɪz/'],
      ['wear', 'носить (одежду)'],
    ],
  },
  {
    topicId: 'beg-v-hotels',
    unit: 10,
    rows: [
      ['hotel', 'гостиница', 'egg', '/həʊˈtel/'],
      ['reception', 'стойка регистрации', 'egg'],
      ['lift', 'лифт', 'fish', '/lɪft/'],
      ['floor', 'этаж, пол', 'horse', '/flɔː/'],
      ['bathroom', 'ванная комната', 'car', '/ˈbɑːθruːm/'],
      ['towel', 'полотенце', 'owl', '/ˈtaʊəl/'],
      ['toilet', 'туалет'],
      ['pillow', 'подушка', 'fish', '/ˈpɪləʊ/'],
      ['lamp', 'лампа', 'cat', '/læmp/'],
      ['light', 'свет', 'bike', '/laɪt/'],
      ['remote', 'пульт', 'phone', '/rɪˈməʊt/'],
      ['cupboard', 'шкаф', 'up', '/ˈkʌbəd/'],
      ['pool', 'бассейн', 'boot', '/puːl/'],
      ['spa', 'спа', 'car', '/spɑː/'],
      ['bar', 'бар'],
      ['garden', 'сад', 'car', '/ˈgɑːdn/'],
      ['view', 'вид', 'boot', '/vjuː/'],
      ['double', 'двухместный', 'up', '/ˈdʌbl/'],
      ['single', 'одноместный', 'fish'],
      ['supermarket', 'супермаркет', 'boot', '/ˈsuːpəmɑːkɪt/'],
      ['bank', 'банк', 'cat', '/bæŋk/'],
    ],
  },
  {
    topicId: 'beg-v-prepositions-place',
    unit: 10,
    rows: [
      ['in', 'в', 'fish', '/ɪn/'],
      ['on', 'на', 'clock', '/ɒn/'],
      ['at', 'в, у, на', 'cat', '/æt/'],
      ['under', 'под', 'up', '/ˈʌndə/'],
      ['near', 'рядом с'],
      ['next', 'следующий, рядом', 'egg', '/nekst/'],
    ],
  },
];

export const travelWords: VocabWord[] = makeWords(groups);
